### ISSUE TITLE
Difference between your DSL and graphqlSDL

### ISSUE THREAD

**Issue by melonboy312** [graphql-java/nadel#31]
Excuse me. I tried to find a document which descripts the difference between your DSL and graphqlSDL, but I did not find any doc. Is there a doc?Or there is no diference?

BTW, Thanks for your work! It's quite helpful!

**Comment by kvfedorov** [comment]
@melonboy312 Stitching DSL is defined here: https://github.com/graphql-java/nadel/blob/master/src/main/antlr/StitchingDSL.g4 and GraphQL DSL is here: https://github.com/graphql-java/graphql-java/blob/master/src/main/antlr/GraphqlSDL.g4 StitchingDSL is little bigger to allow stitching expressions.

**Comment by kvfedorov** [comment]
@bbakerman and @andimarek Are there any plans for "standardization" of Nadel stitching DSL? ;-)

**Comment by bbakerman** [comment]
The library is still building out at the moment.  We are in a phase where we are building a graphql gateway AND building out the Nadel library at the same time.

As such Nadel is not ready for external consumption since no API stability can be guaranteed.  Also we have not yet written the extend documentation that some might want from a graphql-java library

**Comment by melonboy312** [comment]
> @melonboy312 Stitching DSL is defined here: https://github.com/graphql-java/nadel/blob/master/src/main/antlr/StitchingDSL.g4 and GraphQL DSL is here: https://github.com/graphql-java/graphql-java/blob/master/src/main/antlr/GraphqlSDL.g4 StitchingDSL is little bigger to allow stitching expressions.
